# Generated by Django 3.0.8 on 2020-07-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190330_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('appliances', 'Appliances'), ('baby', 'Baby'), ('beauty', 'Beauty'), ('books', 'Books'), ('car', 'Car & Bikes'), ('clothing', 'Clothings & Accessories'), ('collectibles', 'Collectibles'), ('computer', 'Computer & Accessories'), ('electronics', 'Electronics'), ('furniture', 'Furniture')], default='', max_length=50),
        ),
    ]
